# Designed to take telemetry from a file and output smoothed versions representing a digital twin and a low-fidelity simulator
# Author: Jeff Schloemer
# Date: 02/10/2023

# pip install pandas

import argparse
import json
import pandas as pd
import numpy as np

# Define the command line arguments
parser = argparse.ArgumentParser(description='Take telemetry data and output it in realtime')
parser.add_argument('input', help='a json file of timestamped telemetry data')

# Parse the command-line arguments
args = parser.parse_args()
tf = []

if args.input.endswith('json'):
    # Load the JSON file into a pandas DataFrame
    data = json.load(open(args.input))
    tf = pd.DataFrame(data["frames"])
else:
    print("Other sources not supported yet")
    exit()

# Convert the timestamps to a pandas datetime format
tf['time'] = pd.to_datetime(tf['time'])

# Try to average a single column

print(tf['fields']['nx_tmp'].head())

tmps = tf['nx_tmp'].to_series()

print(tmps)


# "dest_callsign": "constant",
# "src_callsign": "constant",
# "src_ssid": "constant",
# "dest_ssid": "constant",
# "ctl": "constant",
# "pid": "constant",
# "src_ip_addr": "constant",
# "dst_ip_addr": "constant",
# "src_port": "constant",
# "dst_port": "constant",
# "type": "constant",
# "daughter_atmp": "variable",
# "daughter_btmp": "variable",
# "threev_pltmp": "variable",
# "rf_amptmp": "variable",
# "nx_tmp": "variable",
# "px_tmp": "variable",
# "ny_tmp": "variable",
# "py_tmp": "variable",
# "nz_tmp": "variable",
# "pz_tmp": "variable",
# "atmelpwrcurr": "variable",
# "atmelpwrbusv": "variable",
# "threev_pwrcurr": "variable",
# "threev_pwrbusv": "variable",
# "threev_plpwrcurr": "variable",
# "threev_plpwrbusv": "variable",
# "fivev_plpwrcurr": "variable",
# "fivev_plpwrbusv": "variable",
# "daughter_apwrcurr": "variable",
# "daughter_apwrbusv": "variable",
# "daughter_bpwrcurr": "constant",
# "daughter_bpwrbusv": "constant",
# "nx_intpwrcurr": "variable",
# "nx_intpwrbusv": "variable",
# "nx_extpwrcurr": "variable",
# "nx_extpwrbusv": "variable",
# "px_intpwrcurr": "variable",
# "px_intpwrbusv": "variable",
# "px_extpwrcurr": "variable",
# "px_extpwrbusv": "variable",
# "ny_intpwrcurr": "variable",
# "ny_intpwrbusv": "variable",
# "ny_extpwrcurr": "variable",
# "ny_extpwrbusv": "variable",
# "py_intpwrcurr": "variable",
# "py_intpwrbusv": "variable",
# "py_extpwrcurr": "variable",
# "py_extpwrbusv": "variable",
# "nz_extpwrcurr": "variable",
# "nz_extpwrbusv": "variable",
# "usercputime": "variable",
# "syscputime": "variable",
# "idlecputime": "variable",
# "processes": "variable",
# "memfree": "variable",
# "buffers": "constant",
# "cached": "variable",
# "datafree": "variable",
# "nanderasures": "variable",
# "beaconcnt": "variable",
# "time": "variable",
# "boottime": "variable",
# "long_dur_counter": "variable",
# "adcs_mode": "status",
# "flags": "status",
# "q0_act": "variable",
# "q1_act": "variable",
# "q2_act": "variable",
# "q3_act": "variable",
# "x_rate": "variable",
# "y_rate": "variable",
# "z_rate": "variable",
# "gyro_px": "variable",
# "gyro_py": "variable",
# "gyro_iz": "variable",
# "gyro_pz": "variable",
# "gyro_ix": "variable",
# "gyro_iy": "variable",
# "sol_nxx": "status",
# "sol_nxy": "status",
# "sol_nyx": "status",
# "sol_nyy": "status",
# "sol_nzx": "status",
# "sol_nzy": "status",
# "sol_pxx": "status",
# "sol_pxy": "status",
# "sol_pyx": "status",
# "sol_pyy": "status",
# "mag_nxx": "variable",
# "mag_nxy": "variable",
# "mag_nxz": "variable",
# "mag_pxz": "variable",
# "mag_pxx": "variable",
# "mag_pxy": "variable",
# "mag_nyz": "variable",
# "mag_pyz": "variable",
# "mag_pyx": "variable",
# "mag_pyy": "variable",
# "wheel_rpm": "variable",
# "cam0_status": "status",
# "cam0_temp": "variable",
# "cam0_last_contact": "variable",
# "cam0_pics_remaining": "status",
# "cam0_retry_fails": "status",
# "cam1_status": "status",
# "cam1_temp": "variable",
# "cam1_last_contact": "variable",
# "cam1_pics_remaining": "status",
# "cam1_retry_fails": "status",
# "torqx_pwrcurr": "variable",
# "torqx_pwrbusv": "variable",
# "torqy_pwrcurr": "variable",
# "torqy_pwrbusv": "variable",
# "torqz_pwrcurr": "variable",
# "torqz_pwrbusv": "variable",
# "motor_pwrcurr": "variable",
# "motor_pwrbusv": "constant",
# "pic_panel_flags": "status",
# "motor_cnt": "status",
# "motor_limit": "status",
# "bat0_curr": "variable",
# "bat0_volt": "variable",
# "bat0_temp": "variable",
# "bat0_flags": "status",
# "bat0_ctlflags": "status",
# "bat1_curr": "variable",
# "bat1_volt": "variable",
# "bat1_temp": "variable",
# "bat1_flags": "status",
# "bat1_ctlflags": "status",
# "bat2_curr": "variable",
# "bat2_volt": "variable",
# "bat2_temp": "variable",
# "bat2_flags": "status",
# "bat2_ctlflags": "status",
# "bat3_curr": "variable",
# "bat3_volt": "variable",
# "bat3_temp": "variable",
# "bat3_flags": "status",
# "bat3_ctlflags": "status",
# "bat4_curr": "variable",
# "bat4_volt": "variable",
# "bat4_temp": "variable",
# "bat4_flags": "status",
# "bat4_ctlflags": "status",
# "bat5_curr": "variable",
# "bat5_volt": "variable",
# "bat5_temp": "variable",
# "bat5_flags": "status",
# "bat5_ctlflags": "status",
# "bat6_curr": "variable",
# "bat6_volt": "variable",
# "bat6_temp": "variable",
# "bat6_flags": "status",
# "bat6_ctlflags": "status",
# "bat7_curr": "variable",
# "bat7_volt": "variable",
# "bat7_temp": "variable",
# "bat7_flags": "status",
# "bat7_ctlflags": "status",
# "comm_rxcount": "variable",
# "comm_txcount": "variable",
# "comm_rxbytes": "variable",
# "comm_txbytes": "variable",
# "Planetary K 12-15": "status",
# "College K 6-9": "variable",
# "Planetary K 18-21": "status",
# "College K 9-12": "variable",
# "College K 21-24": "variable",
# "Fredericksburg K 9-12": "variable",
# "Fredericksburg K 3-6": "variable",
# "College K 3-6": "variable",
# "Planetary A": "status",
# "Fredericksburg A": "variable",
# "Planetary K 21-24": "status",
# "Fredericksburg K 6-9": "variable",
# "College K 12-15": "variable",
# "College K 15-18": "variable",
# "Fredericksburg K 21-24": "variable",
# "College K 0-3": "variable",
# "Fredericksburg K 0-3": "variable",
# "Fredericksburg K 12-15": "variable",
# "Planetary K 9-12": "status",
# "College K 18-21": "variable",
# "Fredericksburg K 18-21": "variable",
# "Fredericksburg K 15-18": "variable",
# "Planetary K 15-18": "status",
# "Planetary K 3-6": "status",
# "College A": "variable",
# "Planetary K 0-3": "status",
# "Planetary K 6-9": "status",
# "Proton 100 MeV": "variable",
# "Electron 2 MeV": "variable",
# "Proton 1 MeV": "variable",
# "Proton 10 MeV": "variable",
# "Neutron": "constant",
# "Electron 800 KeV": "variable",
# "Sunspot Area": "variable",
# "X-Ray S": "status",
# "X-Ray X": "status",
# "SESC sunspot number": "status",
# "X-ray Background Flux": "variable",
# "Optical 3": "constant",
# "Optical 1": "status",
# "Optical 2": "constant",
# "X-Ray M": "status",
# "Solar Mean Field": "constant",
# "Radio Flux": "variable",
# "New Regions": "status",
# "X-Ray C": "status"